---
# tasks file for ansible-minikube
- set_fact:
    ansible_architecture: amd64
    when: 
    - ansible_architecture == "x86_64"

- set_fact:
    ansible_architecture: amd64
    when: 
    - ansible_architecture == "x86_64"

- name: Get latest Release for minikube
  shell: curl -Lo /tmp/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-{{ ansible_system | lower }}-{{ ansible_architecture }}
  args:
    warn: no
  tags: minikube

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/minikube
    dest: /usr/local/bin/minikube
    owner: root
    group: root
    mode: '0755'
  tags: minikube

- name: Verify minikube exists
  stat: path=/usr/local/bin/minikube
  register: minikube_stat
  tags: minikube

- command: minikube version
  register: result_minikube
  failed_when: false
  changed_when: false
  tags: minikube

- debug:
    var: result_minikube.stdout
  tags: minikube